name: Archive

on:
  push:
    branches: [ actions ]

jobs:
  build:
    name: Build archive
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          ARCHIVE_PATH: archive
          SCHEME: DrProxy
        run: xcodebuild archive -scheme ${SCHEME} -archivePath ${ARCHIVE_PATH}
